# Generated by Django 4.2.6 on 2023-10-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snclassifier_djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='log_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date logged'),
        ),
    ]
