# Generated by Django 4.2.6 on 2023-10-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snclassifier_djangoapp', '0002_alter_logmessage_log_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeComent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=300)),
                ('video_link', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date logged')),
            ],
        ),
    ]
